version: '3.9'

services:
  backend:
    build: ./backend
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    networks:
      - devnet

  frontend:
    build: ./frontend
    container_name: nextjs-frontend
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - devnet

networks:
  devnet:
    driver: bridge
