name: CI Pipeline - Build & Push to ECR

on:
  push:
    branches:
      - develop

env:
  AWS_REGION: us-west-1
  ECR_BACKEND: 767397914878.dkr.ecr.us-west-1.amazonaws.com/devops-assignment/backend
  ECR_FRONTEND: 767397914878.dkr.ecr.us-west-1.amazonaws.com/devops-assignment/frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Run Backend Tests
      working-directory: ./backend
      run: |
        pip install -r requirements.txt
        pytest || true  # skip if no tests

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: |
        npm install
        npm run test || true  # skip if no tests

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_BACKEND

    - name: Extract Git SHA
      id: vars
      run: echo "GIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Build & Push Backend Image
      run: |
        docker build -t backend:${{ env.GIT_SHA }} ./backend
        docker tag backend:${{ env.GIT_SHA }} $ECR_BACKEND:${{ env.GIT_SHA }}
        docker push $ECR_BACKEND:${{ env.GIT_SHA }}

    - name: Build & Push Frontend Image
      run: |
        docker build -t frontend:${{ env.GIT_SHA }} ./frontend
        docker tag frontend:${{ env.GIT_SHA }} $ECR_FRONTEND:${{ env.GIT_SHA }}
        docker push $ECR_FRONTEND:${{ env.GIT_SHA }}
